set_property PACKAGE_PIN B1 [get_ports {pl_led[0]}]
set_property PACKAGE_PIN C4 [get_ports {pl_led[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {pl_led[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {pl_led[1]}]

set_property PACKAGE_PIN R17 [get_ports {pl_pmod[0]}]
set_property PACKAGE_PIN U19 [get_ports {pl_pmod[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {pl_pmod[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {pl_pmod[1]}]


### Use PMOD pins #2~#7 here for MDIO #1~#3
set_property PACKAGE_PIN  AA12   [get_ports {sgmii_rxp[0]}]
set_property PACKAGE_PIN  AB12   [get_ports {sgmii_rxn[0]}]
set_property PACKAGE_PIN  AA11   [get_ports {sgmii_txp[0]}]
set_property PACKAGE_PIN  AB11   [get_ports {sgmii_txn[0]}]
set_property PACKAGE_PIN  AB13   [get_ports {sgmii_rxp[1]}]
set_property PACKAGE_PIN  AB14   [get_ports {sgmii_rxn[1]}]
set_property PACKAGE_PIN  Y12    [get_ports {sgmii_txp[1]}]
set_property PACKAGE_PIN  Y13    [get_ports {sgmii_txn[1]}]
set_property PACKAGE_PIN  AB18   [get_ports {sgmii_rxp[2]}]
set_property PACKAGE_PIN  AB19   [get_ports {sgmii_rxn[2]}]
set_property PACKAGE_PIN  AB16   [get_ports {sgmii_txp[2]}]
set_property PACKAGE_PIN  AB17   [get_ports {sgmii_txn[2]}]
set_property PACKAGE_PIN  AB21   [get_ports {sgmii_rxp[3]}]
set_property PACKAGE_PIN  AB22   [get_ports {sgmii_rxn[3]}]
set_property PACKAGE_PIN  AA19   [get_ports {sgmii_txp[3]}]
set_property PACKAGE_PIN  AA20   [get_ports {sgmii_txn[3]}]
set_property PACKAGE_PIN  Y14    [get_ports {sgmii_refclk_p}]
set_property PACKAGE_PIN  Y15    [get_ports {sgmii_refclk_n}]
set_property PACKAGE_PIN  W16    [get_ports {mdio_mdc}]
set_property PACKAGE_PIN  W17    [get_ports {mdio_mdio}]
### set_property PACKAGE_PIN  W15    [get_ports {pl_phy_flnkfail}]
### set_property PACKAGE_PIN  AA14   [get_ports {pl_phy_rcvrd_clk}]
### set_property PACKAGE_PIN  AA17   [get_ports {pl_phy_1588_ls}]

set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_rxp[0]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_rxn[0]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_txp[0]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_txn[0]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_rxp[1]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_rxn[1]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_txp[1]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_txn[1]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_rxp[2]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_rxn[2]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_txp[2]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_txn[2]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_rxp[3]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_rxn[3]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_txp[3]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_txn[3]}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_refclk_p}]
set_property IOSTANDARD    LVDS_25     [get_ports {sgmii_refclk_n}]
set_property IOSTANDARD    LVCMOS25    [get_ports {mdio_mdc}]
set_property IOSTANDARD    LVCMOS25    [get_ports {mdio_mdio}]